-- Generated seed — do not hand-edit. Regenerate via scripts/seed-catalog.ts
insert into categories (slug, name_en, image, sort) values ('indoor', 'Indoor Plants', '/images/cat-indoor.jpg', 0)
  on conflict (slug) do update set name_en = excluded.name_en, image = excluded.image, sort = excluded.sort;
insert into categories (slug, name_en, image, sort) values ('outdoor', 'Outdoor Plants', '/images/cat-outdoor.jpg', 1)
  on conflict (slug) do update set name_en = excluded.name_en, image = excluded.image, sort = excluded.sort;
insert into categories (slug, name_en, image, sort) values ('flowering', 'Flowering Plants & Shrubs', '/images/cat-flowering.jpg', 2)
  on conflict (slug) do update set name_en = excluded.name_en, image = excluded.image, sort = excluded.sort;
insert into categories (slug, name_en, image, sort) values ('trees', 'Trees & Palms', '/images/cat-trees.jpg', 3)
  on conflict (slug) do update set name_en = excluded.name_en, image = excluded.image, sort = excluded.sort;
insert into categories (slug, name_en, image, sort) values ('bonsai', 'Bonsai & Exotic Plants', '/images/cat-bonsai.jpg', 4)
  on conflict (slug) do update set name_en = excluded.name_en, image = excluded.image, sort = excluded.sort;
insert into categories (slug, name_en, image, sort) values ('succulents', 'Succulents & Cacti', '/images/cat-succulents.jpg', 5)
  on conflict (slug) do update set name_en = excluded.name_en, image = excluded.image, sort = excluded.sort;
insert into categories (slug, name_en, image, sort) values ('supplies', 'Garden Supplies, Pots & Decor', '/images/cat-supplies.jpg', 6)
  on conflict (slug) do update set name_en = excluded.name_en, image = excluded.image, sort = excluded.sort;
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'flowering'), 'dahlias', 'Dahlia Varieties', 'Lavender, red, hot pink, cream, bicolour and speckled dahlia varieties.', '{"group":"Dahlia Collection"}'::jsonb, '[{"src":"/images/products/flowering/dahlia/dahlia-lavender-01.jpg","alt":"Lavender pink dahlia"},{"src":"/images/products/flowering/dahlia/dahlia-red-01.jpg","alt":"Red dahlia"},{"src":"/images/products/flowering/dahlia/dahlia-hot-pink-01.jpg","alt":"Hot pink dahlia"},{"src":"/images/products/flowering/dahlia/dahlia-cream-01.jpg","alt":"Cream dahlia"},{"src":"/images/products/flowering/dahlia/dahlia-bicolor-01.jpg","alt":"Burgundy and white dahlia"},{"src":"/images/products/flowering/dahlia/dahlia-speckled-01.jpg","alt":"Speckled cream dahlia"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'flowering'), 'chrysanthemums', 'Chrysanthemum / Gul-e-Daudi', 'Bronze, yellow, red, pink and lilac chrysanthemum selections.', '{"group":"Winter Flower Favourites"}'::jsonb, '[{"src":"/images/products/flowering/chrysanthemum/chrysanthemum-bronze-01.jpg","alt":"Bronze chrysanthemum blooms"},{"src":"/images/products/flowering/chrysanthemum/chrysanthemum-mix-01.jpg","alt":"Orange and purple chrysanthemum mix"},{"src":"/images/products/flowering/chrysanthemum/chrysanthemum-red-pink-01.jpg","alt":"Red and pink chrysanthemum mix"},{"src":"/images/products/flowering/chrysanthemum/chrysanthemum-lilac-01.jpg","alt":"Lilac chrysanthemum cluster"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'flowering'), 'gerberas', 'Gerbera Daisies', 'Colourful gerbera choices from soft blush and cream to rich red and magenta.', '{"group":"Winter Flower Favourites"}'::jsonb, '[{"src":"/images/products/flowering/gerbera/gerbera-coral-01.jpg","alt":"Coral pink gerbera"},{"src":"/images/products/flowering/gerbera/gerbera-magenta-double-01.jpg","alt":"Magenta double gerbera"},{"src":"/images/products/flowering/gerbera/gerbera-red-01.jpg","alt":"Red gerbera"},{"src":"/images/products/flowering/gerbera/gerbera-cream-01.jpg","alt":"Cream gerbera"},{"src":"/images/products/flowering/gerbera/gerbera-blush-01.jpg","alt":"Blush peach gerbera"},{"src":"/images/products/flowering/gerbera/gerbera-light-pink-01.jpg","alt":"Light pink gerbera"},{"src":"/images/products/flowering/gerbera/gerbera-pink-cream-01.jpg","alt":"Pink gerbera with cream centre"},{"src":"/images/products/flowering/gerbera/gerbera-magenta-01.jpg","alt":"Magenta gerbera"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'flowering'), 'primroses', 'Primrose / Primula', 'Compact flowering plants in pink, white, purple and mixed potted colours.', '{"group":"Winter Flower Favourites"}'::jsonb, '[{"src":"/images/products/flowering/primrose/primrose-pink-01.jpg","alt":"Pink primrose flowers"},{"src":"/images/products/flowering/primrose/primrose-magenta-01.jpg","alt":"Magenta primrose flowers"},{"src":"/images/products/flowering/primrose/primrose-white-01.jpg","alt":"White primrose flowers"},{"src":"/images/products/flowering/primrose/primrose-purple-01.jpg","alt":"Purple primrose flowers"},{"src":"/images/products/flowering/primrose/primrose-collection-01.jpg","alt":"Mixed primrose plants in clay pots"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'flowering'), 'marigolds', 'Orange Marigolds / Genda', 'Dense, bright orange marigold plants for cheerful seasonal beds.', '{"group":"Beds, Borders & Climbers"}'::jsonb, '[{"src":"/images/products/flowering/marigold/marigold-orange-bed-01.jpg","alt":"Orange marigold nursery bed"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'flowering'), 'petunias', 'Seasonal Petunias', 'A colourful mix of petunias ready for borders, pots and mass planting.', '{"group":"Beds, Borders & Climbers"}'::jsonb, '[{"src":"/images/products/flowering/petunia/petunia-nursery-bed-01.jpg","alt":"Colourful seasonal petunia nursery bed"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'flowering'), 'bougainvillea', 'Red Bougainvillea', 'A vigorous, sun-loving flowering climber for walls, gates and verandas.', '{"group":"Beds, Borders & Climbers"}'::jsonb, '[{"src":"/images/products/flowering/bougainvillea/bougainvillea-red-01.jpg","alt":"Red bougainvillea at a house frontage"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'indoor'), 'aglaonema', 'Aglaonema / Chinese Evergreen', 'Green, silver and white variegated aglaonema forms for bright, indirect light.', '{"group":"Leafy Indoor Favourites"}'::jsonb, '[{"src":"/images/products/indoor/aglaonema/aglaonema-snow-white-01.jpg","alt":"White variegated aglaonema"},{"src":"/images/products/indoor/aglaonema/aglaonema-silver-green-01.jpg","alt":"Silver-green aglaonema"},{"src":"/images/products/indoor/aglaonema/aglaonema-green-01.jpg","alt":"Green variegated aglaonema"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'indoor'), 'pothos-philodendron', 'Pothos & Philodendron Climbers', 'Marble queen pothos and lemon-lime philodendron trained on coir moss poles.', '{"group":"Leafy Indoor Favourites"}'::jsonb, '[{"src":"/images/products/indoor/pothos-philodendron/pothos-marble-queen-01.jpg","alt":"Marble queen pothos on a moss pole"},{"src":"/images/products/indoor/pothos-philodendron/philodendron-lemon-lime-01.jpg","alt":"Lemon-lime philodendron climbers"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'indoor'), 'dracaena', 'Dracaena Collection', 'Lemon-lime, Song of India and marginata dracaena forms with striking foliage.', '{"group":"Leafy Indoor Favourites"}'::jsonb, '[{"src":"/images/products/indoor/dracaena/dracaena-lemon-lime-01.jpg","alt":"Dracaena lemon lime"},{"src":"/images/products/indoor/dracaena/dracaena-song-of-india-01.jpg","alt":"Variegated Song of India dracaena"},{"src":"/images/products/indoor/dracaena/dracaena-marginata-01.jpg","alt":"Variegated dracaena marginata"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'indoor'), 'spider-plant', 'Variegated Spider Plant', 'A dependable striped foliage plant for baskets, table pots and shaded edges.', '{"group":"Leafy Indoor Favourites"}'::jsonb, '[{"src":"/images/products/indoor/spider-plant/spider-plant-variegated-01.jpg","alt":"Variegated spider plants"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'outdoor'), 'cordyline', 'Cordyline / Ti Plant', 'Pink and red cordyline selections with strong architectural colour.', '{"group":"Colourful Foliage Plants"}'::jsonb, '[{"src":"/images/products/outdoor/cordyline/cordyline-pink-01.jpg","alt":"Pink cordyline plants"},{"src":"/images/products/outdoor/cordyline/cordyline-red-01.jpg","alt":"Red cordyline nursery bed"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'outdoor'), 'crotons', 'Croton Collection', 'Mixed, pink-variegated and gold-dust crotons for vivid all-season foliage.', '{"group":"Colourful Foliage Plants"}'::jsonb, '[{"src":"/images/products/outdoor/croton/croton-mixed-01.jpg","alt":"Mixed croton collection"},{"src":"/images/products/outdoor/croton/croton-pink-01.jpg","alt":"Pink variegated crotons"},{"src":"/images/products/outdoor/croton/croton-gold-dust-01.jpg","alt":"Narrow-leaf gold-dust crotons"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'outdoor'), 'variegated-ginger', 'Variegated Ginger', 'Soft green and cream striped foliage for lush tropical planting schemes.', '{"group":"Colourful Foliage Plants"}'::jsonb, '[{"src":"/images/products/outdoor/variegated-ginger/variegated-ginger-01.jpg","alt":"Variegated ginger foliage"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'trees'), 'jacaranda', 'Jacaranda', 'A striking purple-flowering shade tree.', '{"group":"Flowering Trees"}'::jsonb, '[{"src":"/images/products/trees/flowering-trees/jacaranda-purple-01.jpg","alt":"Purple jacaranda tree"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'trees'), 'trumpet-trees', 'Trumpet Trees', 'Yellow and pink flowering trumpet tree selections.', '{"group":"Flowering Trees"}'::jsonb, '[{"src":"/images/products/trees/flowering-trees/golden-trumpet-tree-01.jpg","alt":"Yellow flowering trumpet tree"},{"src":"/images/products/trees/flowering-trees/pink-trumpet-tree-01.jpg","alt":"Pink flowering trumpet tree"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'trees'), 'show-trees', 'Show-Flowering Trees', 'Pink shower tree, royal poinciana, crape myrtle and magnolia varieties.', '{"group":"Flowering Trees"}'::jsonb, '[{"src":"/images/products/trees/flowering-trees/pink-shower-tree-01.jpg","alt":"Pink shower tree"},{"src":"/images/products/trees/flowering-trees/royal-poinciana-01.jpg","alt":"Red royal poinciana tree"},{"src":"/images/products/trees/flowering-trees/crape-myrtle-purple-01.jpg","alt":"Purple crape myrtle"},{"src":"/images/products/trees/flowering-trees/crape-myrtle-red-01.jpg","alt":"Red crape myrtle"},{"src":"/images/products/trees/flowering-trees/magnolia-white-01.jpg","alt":"White magnolia tree"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'trees'), 'mango-chayote', 'Mango & Chayote', 'Red-skinned mango variety and chayote vine selection.', '{"group":"Fruit & Specialty Plants"}'::jsonb, '[{"src":"/images/products/trees/fruit-trees/mango-red-skin-01.jpg","alt":"Red-skinned mango variety"},{"src":"/images/products/trees/fruit-trees/chayote-01.jpg","alt":"Chayote fruit growing on vine"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'trees'), 'pomegranate-guava', 'Pomegranate & Pink Guava', 'Red Liner pomegranate and Thai pink guava varieties.', '{"group":"Fruit & Specialty Plants"}'::jsonb, '[{"src":"/images/products/trees/fruit-trees/pomegranate-red-liner-01.jpg","alt":"Red Liner pomegranate"},{"src":"/images/products/trees/fruit-trees/guava-thai-pink-01.jpg","alt":"Thai pink guava"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'trees'), 'berries-stone-fruit', 'Berries & Cherry Plum', 'Mulberry, blackberry, red raspberry and cherry plum selections.', '{"group":"Fruit & Specialty Plants"}'::jsonb, '[{"src":"/images/products/trees/fruit-trees/mulberry-01.jpg","alt":"Mulberry fruit"},{"src":"/images/products/trees/fruit-trees/blackberry-01.jpg","alt":"Blackberries"},{"src":"/images/products/trees/fruit-trees/raspberry-red-01.jpg","alt":"Red raspberries"},{"src":"/images/products/trees/fruit-trees/cherry-plum-01.jpg","alt":"Cherry plums on a branch"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'trees'), 'specialty-fruit', 'Specialty Fruit Plants', 'Water apple, striped fig, golden pineapple and jackfruit selections.', '{"group":"Fruit & Specialty Plants"}'::jsonb, '[{"src":"/images/products/trees/fruit-trees/water-apple-01.jpg","alt":"Water apple fruit"},{"src":"/images/products/trees/fruit-trees/fig-striped-01.jpg","alt":"Striped fig variety"},{"src":"/images/products/trees/fruit-trees/pineapple-golden-01.jpg","alt":"Golden pineapple"},{"src":"/images/products/trees/fruit-trees/jackfruit-giant-01.jpg","alt":"Jackfruit"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'supplies'), 'decorative-planters', 'Decorative Planter Collection', 'A broad range of large indoor and outdoor planters in textured finishes.', '{"group":"Planters & Pots"}'::jsonb, '[{"src":"/images/products/garden-decor/planters/decorative-planters-collection-01.jpg","alt":"Large collection of decorative planters"},{"src":"/images/products/garden-decor/planters/tall-planters-collection-01.jpg","alt":"Tall grey and brown planters"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'supplies'), 'carved-planters', 'Carved & Relief Planters', 'Square, rectangular and leaf-relief planters with detailed ornamental texture.', '{"group":"Planters & Pots"}'::jsonb, '[{"src":"/images/products/garden-decor/planters/square-ornamental-planters-01.jpg","alt":"Square carved planters"},{"src":"/images/products/garden-decor/planters/rectangular-planters-01.jpg","alt":"Long carved rectangular planters"},{"src":"/images/products/garden-decor/planters/leaf-relief-planter-01.jpg","alt":"Grey planter with leaf relief"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'supplies'), 'tiered-fountains', 'Tiered Water Fountains', 'Brown and grey standing fountain designs with bowls for cascading water.', '{"group":"Garden Water Features"}'::jsonb, '[{"src":"/images/products/garden-decor/fountains/fountain-brown-tiered-01.jpg","alt":"Brown tiered water fountain"},{"src":"/images/products/garden-decor/fountains/fountain-grey-tiered-01.jpg","alt":"Grey tiered water fountain"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'supplies'), 'feature-fountains', 'Statement Fountains', 'Leaf, geometric and wall-style designs for distinctive garden corners.', '{"group":"Garden Water Features"}'::jsonb, '[{"src":"/images/products/garden-decor/fountains/fountain-leaf-cascade-01.jpg","alt":"Leaf-shaped cascade water fountain"},{"src":"/images/products/garden-decor/fountains/fountain-geometric-cascade-01.jpg","alt":"Geometric cascade water fountain"},{"src":"/images/products/garden-decor/fountains/fountain-wall-cascade-01.jpg","alt":"Wall cascade water fountain"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into products (category_id, slug, name_en, description, attrs, images, status)
  values ((select id from categories where slug = 'supplies'), 'garden-benches', 'Ornamental Garden Benches', 'Yellow decorative benches with sculpted details and sturdy dark bases.', '{"group":"Garden Seating"}'::jsonb, '[{"src":"/images/products/garden-decor/benches/garden-bench-yellow-01.jpg","alt":"Yellow ornamental garden bench"},{"src":"/images/products/garden-decor/benches/garden-benches-daisy-wall-01.jpg","alt":"Yellow benches against floral mural"}]'::jsonb, 'published')
  on conflict (category_id, slug) do update set name_en = excluded.name_en, description = excluded.description, attrs = excluded.attrs, images = excluded.images, status = 'published';
insert into site_settings (key, value) values ('contacts', '[{"owner":"Malik Imran","display":"0300 612 1225","tel":"+923006121225","wa":"923006121225"},{"owner":"Malik Afzaal","display":"0300 712 3618","tel":"+923007123618","wa":"923007123618"}]'::jsonb)
  on conflict (key) do update set value = excluded.value;
insert into site_settings (key, value) values ('contact', '{"name":"Ajmal Garden Nursery","phoneDisplay":"0300 612 1225","phoneTel":"+923006121225","whatsapp":"923006121225","addressLines":["Shatab Garh Road","(near Shahab Poora Road Railway Phatak)","Ajmal Garden Colony, Sialkot","Punjab 51310, Pakistan"],"mapQuery":"Ajmal Garden Colony, Shatab Garh Road, Sialkot, Punjab 51310, Pakistan"}'::jsonb)
  on conflict (key) do update set value = excluded.value;
insert into site_settings (key, value) values ('hours', '"Open daily 6:00 AM – 8:00 PM, 7 days a week."'::jsonb)
  on conflict (key) do update set value = excluded.value;
insert into site_settings (key, value) values ('maps_url', '"https://maps.app.goo.gl/j2sW11SwMc1kwFyA6"'::jsonb)
  on conflict (key) do update set value = excluded.value;
insert into site_settings (key, value) values ('socials', '{"facebook":"https://www.facebook.com/ajmalgarden12","instagram":"https://www.instagram.com/ajmal_garden_nursery/"}'::jsonb)
  on conflict (key) do update set value = excluded.value;
insert into site_settings (key, value) values ('tagline', '"Sialkot - Since 1958"'::jsonb)
  on conflict (key) do update set value = excluded.value;
insert into site_settings (key, value) values ('features', '{"showPrices":false,"showAI":false,"showBulkTable":true}'::jsonb)
  on conflict (key) do update set value = excluded.value;
insert into site_settings (key, value) values ('videos', '[{"id":"4xAZlAmTZZc","title":"Ajmal Garden Nursery — vlog feature 1"},{"id":"SeLV-XQPvl4","title":"Ajmal Garden Nursery — vlog feature 2"},{"id":"QqaaxoTZrfo","title":"Ajmal Garden Nursery — vlog feature 3"},{"id":"IgL4WqkOMt4","title":"Ajmal Garden Nursery — vlog feature 4"}]'::jsonb)
  on conflict (key) do update set value = excluded.value;
